before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...
project_name: trading212-to-stockopedia
builds:
  - main: ./cmd/trading212-to-stockopedia
    id: "trading212-to-stockopedia"
    binary: trading212-to-stockopedia
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
dockers:
  - image_templates:
      - "gsdevme/trading212-to-stockopedia:latest"
      - "gsdevme/trading212-to-stockopedia:{{ .Tag }}"
      - "gsdevme/trading212-to-stockopedia:v{{ .Major }}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'